
package cloud.data.integration.common.journalimport.webservice;

import java.util.List;
import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "JournalImportService", targetNamespace = "http://xmlns.oracle.com/apps/financials/generalLedger/journals/desktopEntry/journalImportService/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface JournalImportService {


    /**
     * 
     * @param interfaceRows
     * @return
     *     returns long
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/generalLedger/journals/desktopEntry/journalImportService/importJournals")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/financials/generalLedger/journals/desktopEntry/journalImportService/types/")
    @RequestWrapper(localName = "importJournals", targetNamespace = "http://xmlns.oracle.com/apps/financials/generalLedger/journals/desktopEntry/journalImportService/types/", className = "cloud.data.integration.common.journalimport.webservice.ImportJournals")
    @ResponseWrapper(localName = "importJournalsResponse", targetNamespace = "http://xmlns.oracle.com/apps/financials/generalLedger/journals/desktopEntry/journalImportService/types/", className = "cloud.data.integration.common.journalimport.webservice.ImportJournalsResponse")
    public long importJournals(
        @WebParam(name = "interfaceRows", targetNamespace = "http://xmlns.oracle.com/apps/financials/generalLedger/journals/desktopEntry/journalImportService/types/")
        GlInterfaceTransHeader interfaceRows)
        throws ServiceException
    ;

    /**
     * 
     * @param interfaceRows
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/generalLedger/journals/desktopEntry/journalImportService/importJournalsAsync")
    @Oneway
    @RequestWrapper(localName = "importJournalsAsync", targetNamespace = "http://xmlns.oracle.com/apps/financials/generalLedger/journals/desktopEntry/journalImportService/types/", className = "cloud.data.integration.common.journalimport.webservice.ImportJournalsAsync")
    public void importJournalsAsync(
        @WebParam(name = "interfaceRows", targetNamespace = "http://xmlns.oracle.com/apps/financials/generalLedger/journals/desktopEntry/journalImportService/types/")
        GlInterfaceTransHeader interfaceRows);

    /**
     * 
     * @param viewName
     * @param localeName
     * @return
     *     returns cloud.data.integration.common.journalimport.webservice.ObjAttrHints
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/generalLedger/journals/desktopEntry/journalImportService/getDfltObjAttrHints")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/financials/generalLedger/journals/desktopEntry/journalImportService/types/")
    @RequestWrapper(localName = "getDfltObjAttrHints", targetNamespace = "http://xmlns.oracle.com/apps/financials/generalLedger/journals/desktopEntry/journalImportService/types/", className = "cloud.data.integration.common.journalimport.webservice.GetDfltObjAttrHints")
    @ResponseWrapper(localName = "getDfltObjAttrHintsResponse", targetNamespace = "http://xmlns.oracle.com/apps/financials/generalLedger/journals/desktopEntry/journalImportService/types/", className = "cloud.data.integration.common.journalimport.webservice.GetDfltObjAttrHintsResponse")
    public ObjAttrHints getDfltObjAttrHints(
        @WebParam(name = "viewName", targetNamespace = "http://xmlns.oracle.com/apps/financials/generalLedger/journals/desktopEntry/journalImportService/types/")
        String viewName,
        @WebParam(name = "localeName", targetNamespace = "http://xmlns.oracle.com/apps/financials/generalLedger/journals/desktopEntry/journalImportService/types/")
        String localeName)
        throws ServiceException
    ;

    /**
     * 
     * @return
     *     returns javax.xml.datatype.XMLGregorianCalendar
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/generalLedger/journals/desktopEntry/journalImportService/getServiceLastUpdateTime")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/financials/generalLedger/journals/desktopEntry/journalImportService/types/")
    @RequestWrapper(localName = "getServiceLastUpdateTime", targetNamespace = "http://xmlns.oracle.com/apps/financials/generalLedger/journals/desktopEntry/journalImportService/types/", className = "cloud.data.integration.common.journalimport.webservice.GetServiceLastUpdateTime")
    @ResponseWrapper(localName = "getServiceLastUpdateTimeResponse", targetNamespace = "http://xmlns.oracle.com/apps/financials/generalLedger/journals/desktopEntry/journalImportService/types/", className = "cloud.data.integration.common.journalimport.webservice.GetServiceLastUpdateTimeResponse")
    public XMLGregorianCalendar getServiceLastUpdateTime()
        throws ServiceException
    ;

    /**
     * 
     * @return
     *     returns java.util.List<cloud.data.integration.common.journalimport.webservice.ServiceViewInfo>
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/generalLedger/journals/desktopEntry/journalImportService/getEntityList")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/financials/generalLedger/journals/desktopEntry/journalImportService/types/")
    @RequestWrapper(localName = "getEntityList", targetNamespace = "http://xmlns.oracle.com/apps/financials/generalLedger/journals/desktopEntry/journalImportService/types/", className = "cloud.data.integration.common.journalimport.webservice.GetEntityList")
    @ResponseWrapper(localName = "getEntityListResponse", targetNamespace = "http://xmlns.oracle.com/apps/financials/generalLedger/journals/desktopEntry/journalImportService/types/", className = "cloud.data.integration.common.journalimport.webservice.GetEntityListResponse")
    public List<ServiceViewInfo> getEntityList()
        throws ServiceException
    ;

    /**
     * 
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/generalLedger/journals/desktopEntry/journalImportService/getEntityListAsync")
    @Oneway
    @RequestWrapper(localName = "getEntityListAsync", targetNamespace = "http://xmlns.oracle.com/apps/financials/generalLedger/journals/desktopEntry/journalImportService/types/", className = "cloud.data.integration.common.journalimport.webservice.GetEntityListAsync")
    public void getEntityListAsync();

    /**
     * 
     * @param viewName
     * @param localeName
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/generalLedger/journals/desktopEntry/journalImportService/getDfltObjAttrHintsAsync")
    @Oneway
    @RequestWrapper(localName = "getDfltObjAttrHintsAsync", targetNamespace = "http://xmlns.oracle.com/apps/financials/generalLedger/journals/desktopEntry/journalImportService/types/", className = "cloud.data.integration.common.journalimport.webservice.GetDfltObjAttrHintsAsync")
    public void getDfltObjAttrHintsAsync(
        @WebParam(name = "viewName", targetNamespace = "http://xmlns.oracle.com/apps/financials/generalLedger/journals/desktopEntry/journalImportService/types/")
        String viewName,
        @WebParam(name = "localeName", targetNamespace = "http://xmlns.oracle.com/apps/financials/generalLedger/journals/desktopEntry/journalImportService/types/")
        String localeName);

    /**
     * 
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/generalLedger/journals/desktopEntry/journalImportService/getServiceLastUpdateTimeAsync")
    @Oneway
    @RequestWrapper(localName = "getServiceLastUpdateTimeAsync", targetNamespace = "http://xmlns.oracle.com/apps/financials/generalLedger/journals/desktopEntry/journalImportService/types/", className = "cloud.data.integration.common.journalimport.webservice.GetServiceLastUpdateTimeAsync")
    public void getServiceLastUpdateTimeAsync();

}
