//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.13 at 12:35:29 PM EDT 
//


package cloud.data.integration.module.journal.report.jaxb.journalCategory;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="P_USER_JE_CATEGORY_NAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="GENERAL_LEDGER_JOURNAL_CATEGORY" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="USER_JE_CATEGORY_NAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "puserjecategoryname",
    "generalledgerjournalcategory"
})
@XmlRootElement(name = "JOURNAL_CATEGORY_DATA")
public class JOURNALCATEGORYDATA {

    @XmlElement(name = "P_USER_JE_CATEGORY_NAME", required = true)
    protected String puserjecategoryname;
    @XmlElement(name = "GENERAL_LEDGER_JOURNAL_CATEGORY", required = true)
    protected List<JOURNALCATEGORYDATA.GENERALLEDGERJOURNALCATEGORY> generalledgerjournalcategory;

    /**
     * Gets the value of the puserjecategoryname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPUSERJECATEGORYNAME() {
        return puserjecategoryname;
    }

    /**
     * Sets the value of the puserjecategoryname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPUSERJECATEGORYNAME(String value) {
        this.puserjecategoryname = value;
    }

    /**
     * Gets the value of the generalledgerjournalcategory property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the generalledgerjournalcategory property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGENERALLEDGERJOURNALCATEGORY().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JOURNALCATEGORYDATA.GENERALLEDGERJOURNALCATEGORY }
     * 
     * 
     */
    public List<JOURNALCATEGORYDATA.GENERALLEDGERJOURNALCATEGORY> getGENERALLEDGERJOURNALCATEGORY() {
        if (generalledgerjournalcategory == null) {
            generalledgerjournalcategory = new ArrayList<JOURNALCATEGORYDATA.GENERALLEDGERJOURNALCATEGORY>();
        }
        return this.generalledgerjournalcategory;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="USER_JE_CATEGORY_NAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "userjecategoryname"
    })
    public static class GENERALLEDGERJOURNALCATEGORY {

        @XmlElement(name = "USER_JE_CATEGORY_NAME", required = true)
        protected String userjecategoryname;

        /**
         * Gets the value of the userjecategoryname property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUSERJECATEGORYNAME() {
            return userjecategoryname;
        }

        /**
         * Sets the value of the userjecategoryname property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUSERJECATEGORYNAME(String value) {
            this.userjecategoryname = value;
        }

    }

}
