
package gov.stcroix.journalimport.client;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ServiceCatalogService", targetNamespace = "http://xmlns.oracle.com/oracle/apps/fnd/applcore/webservices/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServiceCatalogService {


    /**
     * 
     * @param qname
     * @return
     *     returns gov.stcroix.journalimport.client.CatalogService
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/oracle/apps/fnd/applcore/webservices/getServiceEndPoint")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/oracle/apps/fnd/applcore/webservices/types/")
    @RequestWrapper(localName = "getServiceEndPoint", targetNamespace = "http://xmlns.oracle.com/oracle/apps/fnd/applcore/webservices/types/", className = "gov.stcroix.journalimport.client.GetServiceEndPoint")
    @ResponseWrapper(localName = "getServiceEndPointResponse", targetNamespace = "http://xmlns.oracle.com/oracle/apps/fnd/applcore/webservices/types/", className = "gov.stcroix.journalimport.client.GetServiceEndPointResponse")
    public CatalogService getServiceEndPoint(
        @WebParam(name = "qname", targetNamespace = "http://xmlns.oracle.com/oracle/apps/fnd/applcore/webservices/types/")
        String qname)
        throws ServiceException
    ;

    /**
     * 
     * @param serviceType
     * @return
     *     returns java.util.List<gov.stcroix.journalimport.client.CatalogService>
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/oracle/apps/fnd/applcore/webservices/getAllServiceEndPoints")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/oracle/apps/fnd/applcore/webservices/types/")
    @RequestWrapper(localName = "getAllServiceEndPoints", targetNamespace = "http://xmlns.oracle.com/oracle/apps/fnd/applcore/webservices/types/", className = "gov.stcroix.journalimport.client.GetAllServiceEndPoints")
    @ResponseWrapper(localName = "getAllServiceEndPointsResponse", targetNamespace = "http://xmlns.oracle.com/oracle/apps/fnd/applcore/webservices/types/", className = "gov.stcroix.journalimport.client.GetAllServiceEndPointsResponse")
    public List<CatalogService> getAllServiceEndPoints(
        @WebParam(name = "serviceType", targetNamespace = "http://xmlns.oracle.com/oracle/apps/fnd/applcore/webservices/types/")
        List<String> serviceType)
        throws ServiceException
    ;

}
