//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.14 at 11:17:16 AM EDT 
//


package cloud.data.integration.module.journal.report.jaxb.journalSource;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="P_USER_JE_SOURCE_NAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="GENERAL_LEDGER_JOURNAL_SOURCE" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="USER_JE_SOURCE_NAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "puserjesourcename",
    "generalledgerjournalsource"
})
@XmlRootElement(name = "JOURNAL_SOURCE_DATA")
public class JOURNALSOURCEDATA {

    @XmlElement(name = "P_USER_JE_SOURCE_NAME", required = true)
    protected String puserjesourcename;
    @XmlElement(name = "GENERAL_LEDGER_JOURNAL_SOURCE", required = true)
    protected List<JOURNALSOURCEDATA.GENERALLEDGERJOURNALSOURCE> generalledgerjournalsource;

    /**
     * Gets the value of the puserjesourcename property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPUSERJESOURCENAME() {
        return puserjesourcename;
    }

    /**
     * Sets the value of the puserjesourcename property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPUSERJESOURCENAME(String value) {
        this.puserjesourcename = value;
    }

    /**
     * Gets the value of the generalledgerjournalsource property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the generalledgerjournalsource property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGENERALLEDGERJOURNALSOURCE().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JOURNALSOURCEDATA.GENERALLEDGERJOURNALSOURCE }
     * 
     * 
     */
    public List<JOURNALSOURCEDATA.GENERALLEDGERJOURNALSOURCE> getGENERALLEDGERJOURNALSOURCE() {
        if (generalledgerjournalsource == null) {
            generalledgerjournalsource = new ArrayList<JOURNALSOURCEDATA.GENERALLEDGERJOURNALSOURCE>();
        }
        return this.generalledgerjournalsource;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="USER_JE_SOURCE_NAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "userjesourcename"
    })
    public static class GENERALLEDGERJOURNALSOURCE {

        @XmlElement(name = "USER_JE_SOURCE_NAME", required = true)
        protected String userjesourcename;

        /**
         * Gets the value of the userjesourcename property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUSERJESOURCENAME() {
            return userjesourcename;
        }

        /**
         * Sets the value of the userjesourcename property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUSERJESOURCENAME(String value) {
            this.userjesourcename = value;
        }

    }

}
