
package cloud.data.integration.common.webservice;

import java.util.List;
import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ErpObjectAttachmentService", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ErpObjectAttachmentService {


    /**
     * 
     * @param attachment
     * @return
     *     returns java.util.List<cloud.data.integration.common.webservice.DownloadedAttachment>
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/downloadAttachment")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/")
    @RequestWrapper(localName = "downloadAttachment", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/", className = "cloud.data.integration.common.webservice.DownloadAttachment")
    @ResponseWrapper(localName = "downloadAttachmentResponse", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/", className = "cloud.data.integration.common.webservice.DownloadAttachmentResponse")
    public List<DownloadedAttachment> downloadAttachment(
        @WebParam(name = "attachment", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/")
        DownloadAttachmentDtls attachment)
        throws ServiceException
    ;

    /**
     * 
     * @param attachment
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/downloadAttachmentAsync")
    @Oneway
    @RequestWrapper(localName = "downloadAttachmentAsync", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/", className = "cloud.data.integration.common.webservice.DownloadAttachmentAsync")
    public void downloadAttachmentAsync(
        @WebParam(name = "attachment", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/")
        DownloadAttachmentDtls attachment);

    /**
     * 
     * @param allowDuplicate
     * @param entityName
     * @param attachmentRows
     * @param categoryName
     * @return
     *     returns java.lang.String
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/uploadAttachment")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/")
    @RequestWrapper(localName = "uploadAttachment", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/", className = "cloud.data.integration.common.webservice.UploadAttachment")
    @ResponseWrapper(localName = "uploadAttachmentResponse", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/", className = "cloud.data.integration.common.webservice.UploadAttachmentResponse")
    public String uploadAttachment(
        @WebParam(name = "entityName", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/")
        String entityName,
        @WebParam(name = "categoryName", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/")
        String categoryName,
        @WebParam(name = "allowDuplicate", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/")
        String allowDuplicate,
        @WebParam(name = "attachmentRows", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/")
        List<AttachmentDetails> attachmentRows)
        throws ServiceException
    ;

    /**
     * 
     * @param allowDuplicate
     * @param entityName
     * @param attachmentRows
     * @param categoryName
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/uploadAttachmentAsync")
    @Oneway
    @RequestWrapper(localName = "uploadAttachmentAsync", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/", className = "cloud.data.integration.common.webservice.UploadAttachmentAsync")
    public void uploadAttachmentAsync(
        @WebParam(name = "entityName", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/")
        String entityName,
        @WebParam(name = "categoryName", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/")
        String categoryName,
        @WebParam(name = "allowDuplicate", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/")
        String allowDuplicate,
        @WebParam(name = "attachmentRows", targetNamespace = "http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/")
        List<AttachmentDetails> attachmentRows);

}
